version: '3.7'

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${SERVER_PORT:-8080}:8080
    command: npm run start:dev
    environment:
      - PORT=8080
